#!/bin/bash

# This script resets the Drupal login password of the user specified.
# If no user is provided, the default is the name of uid 1.

# Preconditions:
# 1. A Unix-like operating system such as Mac OSX or Linux
# 2. The current directory must be within a Drupal installation
# 3. The drush command must be available

DRUSH=$(which drush)
if [ $? == 1 ]; then
  echo "Drush is not installed.  See http://www.drush.org/en/master/install."
  exit 1
fi
if test $1; then
  if test $2; then
    name=$2
  else
    name=$($DRUSH uinf --fields=name --pipe 1)
  fi
  $DRUSH upwd $name --password="$1"
  exit $?
else
  DPRF=$(basename $0)
  echo ""
  echo "Resets the Drupal login password of the user specified."
  echo "If no user is provided, the default is the name of uid 1."
  echo ""
  echo "Usage:"
  echo "  $DPRF <password> [<user>]"
  echo ""
  echo "Examples:"
  echo "  $DPRF admin - Reset the password of uid 1 to admin"
  echo "  $DPRF secret bob - Reset the password of user bob to secret"
  echo ""
fi
