#!/bin/bash

# This script will locate any Drupal function or class method and
# edit the file at the start line containing that function or method.
# It will locate core as well as contrib or even custom module
# functions and methods.

# Preconditions:
# 1. A Unix-like operating system such as Mac OSX or Linux
# 2. The current directory must be within a Drupal installation
# 3. The devel contrib module must be installed and enabled
# 4. The drush command must be available
# 5. The vi editor command must be available

if test $1; then
  DRUSH=$(which drush)
  if [ $? == 1 ]; then
    echo "Drush is not installed.  See http://www.drush.org/en/master/install."
    exit 1
  fi
  VI=$(which vi)
  if [ $? == 1 ]; then
    echo "The vi editor is not installed."
    exit 1
  fi
  FILE=$($DRUSH --pipe fnv $1 --format='!file +!startline')
  if [ $? == 1 ]; then
    exit 1
  fi
  if [ ! -z "$FILE" ]; then
    $VI $FILE
  fi
else
  VIF=$(basename $0)
  echo ""
  echo "Usage:"
  echo "  $VIF <Drupal function or class method>"
  echo ""
  echo "Examples:"
  echo "  $VIF user_access"
  echo "  $VIF view::update"
  echo ""
fi
